POST http://localhost:8080/subscriptions
Content-Type: application/json

{
    "name": "Fulano",
    "email": "fulano@email.com",
    "referrer": "b9c2d6d3-8e69-40f4-8fd9-38ebad83bc8f"
}

###

GET  http://localhost:8080/invites/b9c2d6d3-8e69-40f4-8fd9-38ebad83bc8f

###

GET  http://localhost:8080/subscribers/f3b69b4f-bcd8-449b-8eb0-be916f0c6848/ranking/clicks

###

GET  http://localhost:8080/subscribers/b9c2d6d3-8e69-40f4-8fd9-38ebad83bc8f/ranking/count

###

GET  http://localhost:8080/subscribers/b9c2d6d3-8e69-40f4-8fd9-38ebad83bc8f/ranking/position

###

GET  http://localhost:8080/ranking